config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",registrations: "users/registrations",  passwords: "users/passwords", omniauth_callbacks: 'users/omniauth_callbacks'}
   root to: 'homes#index'
   resources :homes do
   	collection do
   		get :csv_exports
   	end
   end

   resources :csv_datums do
   	collection do
   		post :data_csv
   	end
   end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
	has_attached_file :csv_file
 validates_attachment_content_type :csv_file,
 :content_type => ["application/zip", "application/pdf", "application/vnd.ms-excel",
 "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.presentationml.presentation","image/png", "image/jpeg","image/gif","image/jpg","image/tiff", "text/plain","video/mp4","video/avi","audio/mpeg","audio/mp3"]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_sku, only: [:show, :edit, :update, :destroy]
  def index
  	@homes = Home.new
  end
  
  def show;end

  def edit;end

  def update;end

  def destroy;end

  def create
  	@homes = Home.new(homes_params)
  	puts "==================#{@homes.inspect}"
  	if @homes.save
  		flash[:sucess] = "New Denomination Created"
  		redirect_to homes_path
  	else
  		flash[:error] = "New Denomination not Created"
  		redirect_to homes_path	
  	end
  end

  def csv_data
  end	

  def csv_exports
  	if params[:csv_exports].present?
  		@all_data = CsvDatum.all
  		respond_to do |format|
        format.html
        format.csv { send_data CsvDatum.csv_export(@all_data), filename: "#{Date.today}.csv" }
      end
  	end
  end

  private

  def sku
  	@homes = Home.find(params[:id])
  end

  def homes_params
  	params.require(:home).permit(:denomination, :csv_file)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/csv_exports.html.erb
<%= form_for :csv_exports,:url => {:controller => "homes", :action => "csv_exports"},:html=>{:method => 'GET',:id=>"csv_exports", formet: :csv} do |f|%>
<div class="panel-body">
  <div class="row">
    <div class="form-group col-sm-4">
      <label for="reg_input_name" class="req">Start Date</label>
       <%= f.date_field :start_date, :class =>"form-control start-date" %>
    </div>
    <div class="form-group col-sm-4">
      <label for="reg_input_name" class="req">End Date</label>
       <%= f.date_field :end_date, :class =>"form-control end-date" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 text-center" style="margin-bottom: 10px;">
    <%= button_tag( 'Download CSV', :value => 'csv', :name => 'format', :class=>"btn btn-primary" ) %>
  </div>
  <div class="col-sm-4"></div>
</div>
<%end%>

app/views/homes/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand">Assignment</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class=""><a href="/">Home</a></li>
        <li class="active">
        	<%= link_to "Csv Export", csv_exports_homes_path, :class=>""%>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a class="nav-link" data-toggle="modal" data-target="#skuModel"><i class="fa-li fa fa-spinner fa-spin" style="top:17px;"></i></span> SKU Combination Creation</a></li>
        <li><a class="nav-link" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-fw fa-sign-out"></i></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- Logout Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <%= link_to('Logout', destroy_user_session_path, method: :delete,class: "btn btn-primary") %>
                    <!-- <a class="btn btn-primary" href="/users/sign_in">Logout</a> -->
            </div>
        </div>
    </div>
</div>
<!-- sku combination model -->
<div class="modal fade" id="skuModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
            <%= form_tag data_csv_csv_datums_path, multipart: true do %>
              <div class="row">
                <div class="col-sm-12">
                  <div class="panel panel-white">
                  <div class="panel-heading">
                    <h4 class="panel-title">CSV Import</h4>
                  </div>
                    <div class="panel-body">
                      <div class="row">
                        <div class="form-group col-sm-12">
                          <label for="reg_input_name" class="req">Browse File</label>
                          <%= file_field_tag :file %>
                        </div>
                        <div class="col-sm-12">
                        	<label>Sku Denomination</label>
                          <%=text_field_tag :sku_denomination, "", class: "form-control denomination"%>
                        </div>
                      </div>
                      <div class="row" style="margin-top: 10px;">
                        <div class="text-center">
                          <%= submit_tag "Import CSV", :class=> "btn btn-info"%>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
		    </div>
		</div>
		<style type="text/css">
			.star{
		color: red;
		margin-left: 2px;
	}
	.denomination{
		width: 563px;
		margin-left: 12px;
	}
</style>